# Generated by Django 4.2.3 on 2023-07-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'ordering': ['-date_of_purchase']},
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='date_of_purchases',
        ),
        migrations.AddField(
            model_name='purchases',
            name='date_of_purchase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='purchases',
            table='purchases',
        ),
    ]
