# Generated by Django 4.2.3 on 2023-07-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_books', models.TextField()),
                ('author', models.TextField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
