# Generated by Django 4.2.3 on 2023-07-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='books',
            unique_together={('title', 'author')},
        ),
        migrations.RemoveField(
            model_name='books',
            name='name_books',
        ),
    ]
